= AsciiDoc and Asciidoctor Presentation
Jared Morgan; Russell Dickenson

Files relating to the AsciiDoc presentation showcasing HubPress and Asciidoctor technologies.

== Files

<<run-sheet#,run-sheet.adoc>>:: 
  The 'presentation' I displayed in the video.
<<example#,example.adoc>>::
  A very simple AsciiDoc document you can experiment with.

== Video

ifdef::env-github[]
View the https://vimeo.com/129621323[video] on Vimeo.

[TIP]
====
To see how videos appear in `.adoc` files, either:

. View http://gist.asciidoctor.org/?github-jaredmorgs%2FAsciidoctor_Presentation%2F%2FREADME.adoc[this file] on gist.asciidoctor.org
. View the https://raw.githubusercontent.com/jaredmorgs/Asciidoctor_Presentation/master/README.adoc[raw source] of this file with the Asciidoctor.js Live Preview extension for https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[Chrome] or https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/[Firefox] active
. Build this file locally:

 $ asciidoctor README.adoc
+
then view the generated HTML, README.html, in your browser.
====
endif::[]

ifndef::env-github[]
video::129621323[vimeo,960,540] 
endif::[]

The demos start about 20 minutes into the presentation.

== Resources

Get Learning::
  http://asciidoctor.org/ is the place to go to learn more about the fast text processor & publishing toolchain for converting AsciiDoc to HTML5, DocBook & more. On this landing page, you get links to all Asciidoctor Docs. It's a great resource I refer to regularly when writing. 

Get Building::
  https://github.com/jaredmorgs/Pinball_Arcade_Users_Guide_Android is an example of a complete user guide, with include statements and some more advanced AsciiDoc markup. You can practise building this locally by following the instructions in the https://github.com/jaredmorgs/Pinball_Arcade_Users_Guide_Android/blob/master/README.adoc[README.adoc] 

Get Publishing::
  https://github.com/asciidoctor/jekyll-asciidoc-quickstart is a forkable Jekyll site using AsciiDoc. It uses Travis-CI to automatically build and publish your book when you commit changes to the repository. Follow the instructions in the https://github.com/asciidoctor/jekyll-asciidoc-quickstart/blob/master/README.adoc[README.adoc] to get this set up for use. You can use the Users Guide above as a base for your guide, or not worry about includes and have one flat file. 

Get Blogging::
  https://github.com/HubPress/hubpress.io is a forkable Blogging app that uses asciidoctor.js as the transformation engine, and Ghostscript themes to style the blog posts. Follow the instructions in the https://github.com/HubPress/hubpress.io/blob/master/README.adoc[README.adoc] to configure the blog. 

Default to Open::
  All the links above are Free and Open Source (FOSS) projects created with collaboration in mind. If you want to contribute, fork the projects and start contributing. No contribution is too small: a bug fix to spelling, corrections to procedures, anything.
